import React, { useEffect, useContext } from "react";
import Link from "next/link";
import Image from "next/image";
import Head from "next/head";
import Aos from "aos";
import "aos/dist/aos.css";
import { FaGithub, FaLinkedinIn, FaChevronLeft } from "react-icons/fa";
import Profile from "../public/assets/profile.jpg";
import { ThemeContext } from "../context/ThemeContext";

const resume = () => {
  const { theme } = useContext(ThemeContext);

  useEffect(() => {
    Aos.init({
      offset: 200,
      duration: 400,
      easing: "ease-in-sine",
      delay: 100,
    });
  }, []);

  return (
    <div className={!theme ? "dark" : ""}>
      <div className="bg-gray-300 dark:bg-[#00040F]">
        <Head>
          <title>Stefan | Resume</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
          <link
            href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,300;0,500;0,600;0,700;1,300&display=swap"
            rel="stylesheet"
          />
        </Head>
        <div className="p-10 text-xl bg-red flex items-center w-20 text-slate-900 dark:text-gray-200">
          <Link href="/">
            <div className="flex justify-center hover:scale-110 ease-in duration-200">
              <FaChevronLeft />
              <p className="uppercase text-sm">Back</p>
            </div>
          </Link>
        </div>

        <div
          data-aos="fade-up"
          className="max-w-[940px] mx-auto p-2 pt-5 text-gray-400"
        >
          <h2 className="text-center text-slate-800 dark:text-gray-200">
            Resume
          </h2>
          <div className="bg-gradient-to-r from-blue-600 to-slate-800 rounded-md my-4 p-4 w-full flex justify-between items-center">
            <Image
              className="rounded-xl hover:scale-105 ease-in duration-300"
              src={Profile}
              alt="/"
              width={150}
            />
            <div className="flex flex-col items-center justify-evenly">
              <div className="text-center text-gray-200">
                <h2>Stefan Kovačić</h2>
                <h3>Frontend Developer</h3>
              </div>

              <div className="flex items-center">
                <Link
                  href="https://www.linkedin.com/in/stefan-kovacic-bb6599230/"
                  target="_blank"
                  rel="noreferrer"
                >
                  <FaLinkedinIn
                    size={20}
                    style={{ marginRight: "1rem", color: "#FFFFFF" }}
                  />
                </Link>
                <Link
                  href="https://github.com/Kefadev98"
                  target="_blank"
                  rel="noreferrer"
                >
                  <FaGithub
                    size={20}
                    style={{ marginRight: "1rem", color: "#FFFFFF" }}
                  />
                </Link>
              </div>
            </div>
          </div>

          {/*Education*/}
          <div className="shadow-md bg-gray-200 rounded-md dark:bg-transparent shadow-slate-800 dark:shadow-blue-500 p-4 mb-6">
            <div className="py-4 text-xl font-bold uppercase tracking-wider">
              <p className="text-slate-800 dark:text-blue-500">Education</p>
            </div>
            <div>
              <p className="italic text-slate-800 dark:text-gray-100">
                October 2017 – October 2021
              </p>
              <ul className="my-2 mx-5">
                <li className="list-disc text-slate-800 dark:text-gray-200">
                  Enrolled into&nbsp;
                  <span className="font-bold text-slate-800 dark:text-gray-200">
                    „Panevropski Univerzitet APEIRON“&nbsp;
                  </span>
                  in Banja Luka, graduent on time, vocation Graduated Computer
                  Scientist ( Specialist in the field of Computer Engineering),
                  with 240 ECTS credits.
                </li>
              </ul>
              <p className="italic text-slate-800 dark:text-gray-100">
                September 2013 – May 2017
              </p>
              <ul className="my-2 mx-5">
                <li className="list-disc text-slate-800 dark:text-gray-200">
                  Graduated in highschool&nbsp;
                  <span className="font-bold text-slate-800 dark:text-gray-200">
                    „Opšta Gimnazija“&nbsp;
                  </span>
                  in Gradiška.
                </li>
              </ul>
            </div>
          </div>

          {/* Skills */}
          <div className="shadow-md rounded-md bg-gray-200 dark:bg-transparent shadow-slate-800 dark:shadow-blue-500 p-4 mb-6">
            <div className="py-4 text-xl font-bold uppercase tracking-wider">
              <p className="text-slate-800 dark:text-blue-500">Courses</p>
            </div>
            <p className="italic text-slate-800 dark:text-gray-100">
              May 2022 – June 2022
            </p>
            <ul className="my-2 mx-5">
              <li className="list-disc text-slate-800 dark:text-gray-200">
                Enrolled into React online course for Front-end Developer.
              </li>
            </ul>
            <p className="italic text-slate-800 dark:text-gray-100">
              December 2021 – January 2022
            </p>
            <ul className="my-2 mx-5">
              <li className="list-disc text-slate-800 dark:text-gray-200">
                Accomplished a programming course of HTML/CSS and Javascript
              </li>
            </ul>
          </div>

          {/* Experience */}
          <div className="shadow-md rounded-md bg-gray-200 dark:bg-transparent shadow-slate-800 dark:shadow-blue-500 p-4 mb-6">
            <div className="py-4 text-xl font-bold uppercase tracking-wider">
              <p className="text-slate-800 dark:text-blue-500">
                Former employment
              </p>
            </div>
            <p className="italic text-slate-800 dark:text-gray-100">
              February 2022 – November 2022{" "}
            </p>
            <ul className="my-2 mx-5">
              <li className="list-disc text-slate-800 dark:text-gray-200">
                I passed an internship program for Front-end Developers at&nbsp;
                <span className="font-bold text-slate-800 dark:text-gray-200">
                  Quantox Technology
                </span>
                .
              </li>
            </ul>
            <p className="italic text-slate-800 dark:text-gray-100">
              November 2022 – Current
            </p>
            <ul className="my-2 mx-5 text-slate-800 dark:text-gray-200">
              <li className="list-disc text-slate-800 dark:text-gray-200">
                Teaching and mentoring HTML and CSS
              </li>
            </ul>
          </div>

          {/* Sociall skills */}
          <div className="shadow-md rounded-md bg-gray-200 dark:bg-transparent shadow-slate-800 dark:shadow-blue-500 p-4 mb-6">
            <div className="py-4 text-xl font-bold uppercase tracking-wider">
              <p className="text-slate-800 dark:text-blue-500">
                Social skills{" "}
              </p>
            </div>
            <ul className="my-2 mx-5">
              <li className="list-disc text-slate-800 dark:text-gray-200">
                Communicative
              </li>
              <li className="list-disc text-slate-800 dark:text-gray-200">
                Easygoing and friendly
              </li>
              <li className="list-disc text-slate-800 dark:text-gray-200">
                Flexible
              </li>
              <li className="list-disc text-slate-800 dark:text-gray-200">
                Able to multitask on multiple levels
              </li>
              <li className="list-disc text-slate-800 dark:text-gray-200">
                Easily adjustible to different type of situations and group work
              </li>
              <li className="list-disc text-slate-800 dark:text-gray-200">
                Enthusiastic and engaged when interacting with people
              </li>
            </ul>
          </div>

          {/* Experience */}
          <div className="shadow-md rounded-md bg-gray-200 dark:bg-transparent shadow-slate-800 dark:shadow-blue-500 p-4 mb-6">
            <div className="py-4 text-xl font-bold uppercase tracking-wider">
              <p className="text-slate-800 dark:text-blue-500">Technologies </p>
            </div>
            <ul className="my-2 mx-5">
              <li className="list-disc text-slate-800 dark:text-gray-200">
                <span className="font-bold text-slate-800 dark:text-gray-200">
                  HTML5
                </span>{" "}
                – I am able to make a good structure and layout for every
                project from scratch
              </li>
              <li className="list-disc text-slate-800 dark:text-gray-200">
                <span className="font-bold text-slate-800 dark:text-gray-200">
                  CSS
                </span>{" "}
                - I can do all kinds of design and responsive design for tablet
                and mobile, also worked with SCSS preprocessor
              </li>
              <li className="list-disc text-slate-800 dark:text-gray-200">
                <span className="font-bold text-slate-800 dark:text-gray-200">
                  Javascript
                </span>{" "}
                – Learned data types, variables, loops, objects, array methods,
                functions, hoisting, DOM manipulation, asynchronous JS
              </li>
              <li className="list-disc text-slate-800 dark:text-gray-200">
                <span className="font-bold text-slate-800 dark:text-gray-200">
                  React JS
                </span>{" "}
                – Learned hooks and custom hooks, context Api, props,
                conditional rendering, React Query, React Router, React Hook
                Form, pagination, authentication with JWT, also know the basics
                of Redux Toolkit and Redux Toolkit Query.
              </li>
              <li className="list-disc text-slate-800 dark:text-gray-200">
                <span className="font-bold text-slate-800 dark:text-gray-200">
                  Tailwind CSS and Chakra UI
                </span>
                &nbsp; - I am able to quickly implement a design for all screen
                dimensions.
              </li>
              <li className="list-disc text-slate-800 dark:text-gray-200">
                <span className="font-bold text-slate-800 dark:text-gray-200">
                  NextJS fundamentals
                </span>
                &nbsp; – I practiced Server-side and Client-side components,
                SSR, SSG, ISR rendering techniques, routes, new file conventions
              </li>
              <li className="list-disc text-slate-800 dark:text-gray-200">
                <span className="font-bold text-slate-800 dark:text-gray-200">
                  Git and Github
                </span>{" "}
                - I know git commands such as git clone, init, add, push,
                commit, pull, merge, status, branch
              </li>
            </ul>
          </div>

          {/*About me */}
          <div className="shadow-md rounded-md bg-gray-200 dark:bg-transparent shadow-slate-800 dark:shadow-blue-500 p-4 mb-6">
            <div className="py-4 text-xl font-bold uppercase tracking-wider">
              <p className="text-slate-800 dark:text-blue-500">About Me</p>
            </div>
            <p className="text-slate-800 dark:text-gray-200">
              My name is Stefan, I am 24 years old. Graduated Computer Scientist
              with 240 ECTS credits. I would like to apply for the position of
              Junior Front-end Web Developer in your company. I am ready to
              progress everyday with team members and learn new technologies. If
              there is a problem that need's to be adressed I will do my best to
              fulfill my duties. I'm a hardworking and highly adaptive person. I
              don't like leaving any work unfinished. I'm a self motivated and
              dedicated to my work and i can handle the pressure that comes with
              every job. I consider myself a team player. I would be more than
              happy to work in a dynamic environment of a well developed team of
              people where everyone is playing their roles which leads to
              greater overall progress. I specialize in building mobile
              responsive Front-end UI applications that connect with API’s and
              other backend technologies. I am proficient in building front-end
              applications using HTML, CSS, Javascript, and React. My goal in
              the near future is to start taking a new challenges to broaden my
              horisonts and help me advance my knowlege in software development
              which would opet a new path to becoming a better developer. If you
              want to read more about the technologies and libraries I used, you
              can read in the letter of recommendation. For any more information
              I sincerly hope that you will contact me.
            </p>
            <p className="mt-2 text-slate-800 dark:text-gray-200">
              Looking forward to hearing from you.
            </p>
          </div>
        </div>
      </div>
    </div>
  );
};

export default resume;
